export const UPDATE_SIDEBAR_COMPONENT_STATES = "UPDATE_SIDEBAR_COMPONENT_STATES";
export const ADD_ACTIONS_DATA = "ADD_ACTIONS_DATA";
export const DELETE_ACTION_DATA = "DELETE_ACTION_DATA";
export const UPDATE_ACTIONS_DATA = "UPDATE_ACTIONS_DATA";